[FEAT] 퀴즈 정답 확인 API 작성 완료
EFUB-EDAY/EDAY-BACK pull request #13
Opened 2023-07-18 11:21 UTC by hannah0226

# 구현 기능
- 퀴즈 정답 확인

# 구현 상태

![스크린샷 2023-07-18 201830](https://github.com/EFUB-EDAY/EDAY-BACK/assets/89291223/424182e8-1a77-40d5-8d33-5713a85ba6a0)
![스크린샷 2023-07-18 201844](https://github.com/EFUB-EDAY/EDAY-BACK/assets/89291223/720fd4b2-8227-4d8b-bd21-367cf0ca36a9)

# Resolve
- #4

2023-07-19 22:08 UTC, choiyounji commented
선지 true인지 false인지 잘 반환되게 짜셨네요! 추가적으로 이제 true인 경우에는 이제 사용자의 레벨+1해주기, 사용자퀴즈 테이블에 값 추가 등의 로직 구현이 더 필요할 것 같아요!

2023-07-22 03:23 UTC, mingulmangul requested changes

2023-07-22 03:23 UTC, mingulmangul commented on src/main/java/efub/eday/edayback/domain/day/quiz/entity/Quiz.java
혹시 subject 컬럼 이름 `d_day_id`에서 `subject_id`로 변경해주실 수 있나요??

2023-07-22 03:23 UTC, mingulmangul commented on src/main/java/efub/eday/edayback/domain/day/quiz/controller/QuizController.java
> +	}
프론트 입장에서 각 선택지의 optionId가 무엇인지 모르니 OptionsResponseDTO에서 optionId를 줘야할 것 같아요. 근데 DB에서 쓰는 id보다는 첫번째/두번째/세번째 선택지 이렇게 구분하는게 명확할 것 같아요. 이미 같은 의미로 Option 엔티티에 optionNumber를 만들어 주신 것 같은데 이걸 응답에 포함시키고, quizRequestDto에서도 optionId보다 optionNumber로 받는게 좋을 것 같습니다!

2023-07-22 03:23 UTC, mingulmangul commented on src/main/java/efub/eday/edayback/domain/day/quiz/entity/Options.java
>  	}
Option이나 Quiz는 생성할 일이 없으니 생성자나 빌더는 없어도 됩니다! 미리 DB에 제가 넣어둘 거예요

2023-07-22 03:23 UTC, mingulmangul commented on src/main/java/efub/eday/edayback/domain/day/quiz/service/QuizService.java
> +		}
퀴즈 정답 확인 로직은 Quiz 엔티티로 이동해도 좋을 것 같아요. Quiz 클래스 밖에서 optionList를 get으로 불러오지 않아도 되니까요. Quiz 엔티티에서 확인하고 isCorrect를 리턴해주는 방식도 괜찮을 것 같습니다~ 그리고 optionNumber와 option_id를 비교하는데 둘이 이름을 통일하면 좋겠습니다! option_id는 DB에서 쓰는 PK 같으니까 이 이름을 수정해야 더 명확할 것 같아요

2023-07-22 03:23 UTC, mingulmangul commented on src/main/java/efub/eday/edayback/domain/day/quiz/service/QuizService.java
> +			memberTitleRepository.save(memberTitle);
변경사항 있으면 따로 save 안해도 저장되지 않나요??

2023-07-22 03:23 UTC, mingulmangul commented on src/main/java/efub/eday/edayback/domain/day/quiz/service/QuizService.java
정답인지 확인하고 MemberTitle 생성하는 것까지 아주 잘해주셔서 간단한 리팩토링 말고는 수정할 거 없는 것 같습니다! 그런데 MemberTitle뿐만 아니라 MemberQuiz도 생성하거나 isCorrect를 true로 바꿔줘야 해요! 요 로직 추가해주면 좋겠습니다~^^

2023-07-22 04:48 UTC, mingulmangul commented
엔티티 제가 수정했어요!! 풀 받고 작업해주세요!

2023-07-23 04:44 UTC, mingulmangul commented
확인했습니다! 머지할게요~

2023-07-23 04:44 UTC, merged