[Chore] 엔티티 수정에 맞추어 문의사항(Query), 칭호(Title) 코드 수정
EFUB-EDAY/EDAY-BACK pull request #19
Opened 2023-07-22 08:34 UTC by chhaewxn

# 구현 기능
엔티티 코드 수정에 맞추어서 문의사항과 칭호 관련하여 타입(Long -> Integer)로 수정 후에, postman 실습 잘 돌아가는 것 확인하였습니다.

# 구현 상태 
![image](https://github.com/EFUB-EDAY/EDAY-BACK/assets/96541582/7257490a-ce13-4170-8be0-3bafe4a738ac)
![image](https://github.com/EFUB-EDAY/EDAY-BACK/assets/96541582/10a912c9-6a46-40ab-8fe2-fb4ee3a906ff)

![image](https://github.com/EFUB-EDAY/EDAY-BACK/assets/96541582/71155ad5-ab8c-4cdd-b6a0-5d2677d62222)
![image](https://github.com/EFUB-EDAY/EDAY-BACK/assets/96541582/c75d0e38-e92c-45ce-9a9a-a6d412feab74)

2023-07-22 11:50 UTC, mingulmangul requested changes
작은 수정사항 빼고는 다 좋은 것 같아요! 고생많으셨습니다 🥰

2023-07-22 11:50 UTC, mingulmangul commented on src/main/java/efub/eday/edayback/domain/query/dto/QueryRequestDto.java
> +}
이거 API에서는 subjectId가 아니라 디데이로 받기로 해서 수정해주셔야 할 것 같습니다..!

2023-07-22 16:43 UTC, chhaewxn commented on src/main/java/efub/eday/edayback/domain/query/dto/QueryRequestDto.java
> +}
넵! dday 받기로 코드 수정하였습니다😀

2023-07-23 04:54 UTC, mingulmangul commented
확인했습니다 머지할게요~!

2023-07-23 04:54 UTC, merged